### ISSUE TITLE
Xcode 7 problem

### ISSUE THREAD

**Issue by MarvinNazari** [iCodesign/ICSPullToRefresh.Swift#12]
Hi, there is a problem with the Xcode 7 GM and Swift 2

```
   public override func observeValueForKeyPath(keyPath: String?, ofObject object: AnyObject?, change: [String : AnyObject]?, context: UnsafeMutablePointer<Void>) {
    if keyPath == observeKeyContentOffset {
        srollViewDidScroll(change[NSKeyValueChangeNewKey]?.CGPointValue)
    } else if keyPath == observeKeyFrame {
        setNeedsLayout()
    }
}
```

the error is: Cannot subscript a value of type '[String : AnyObject]?' with an index of type 'String'

**Comment by icodesign** [comment]
@MarvinNazari Thanks for you issue. It has been resolved with new version `0.2`. See 48bb6661a3c93154e587106f288a68e719eaf800.
