### ISSUE TITLE
infiniteScrollingView是否可以在接近底部的位置预先展示一个loading状态的indicator？

### ISSUE THREAD

**Issue by lukedesu** [iCodesign/ICSPullToRefresh.Swift#17]
hello wanglei,

我发现目前的版本在下拉到尾部的时候给人的感觉不太友好，是否可以在接近尾部的时候预先加载一个loading状态的indicator？

另外顶部下拉的时候，如果在网速过快的时候是否可以人为的增加一点延迟时间，否则给人感觉是下拉无效，而且loading的菊花也不会转动（我不确定是不是我的网速太快了....）

谢谢~

**Comment by icodesign** [comment]
> 我发现目前的版本在下拉到尾部的时候给人的感觉不太友好，是否可以在接近尾部的时候预先加载一个loading状态的indicator？

目前底部是有 indicator 的吧，不知道你能不能给个截图

> 如果在网速过快的时候是否可以人为的增加一点延迟时间，否则给人感觉是下拉无效，而且loading的菊花也不会转动

这个你可以人为的加一下延时
