### ISSUE TITLE
Handler retain cycle

### ISSUE THREAD

**Issue by diegogarciar** [iCodesign/ICSPullToRefresh.Swift#29]
I recently ran into the issue that my view controller had a retain cycle in the pullToRefresh handler. I don't think that there needs something to be changed, but I do suggest that you add a `[weak self]` in your example as follows:

```
tableView.addPullToRefreshHandler { [weak self] in
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), { () -> Void in
        // do something in the background
        dispatch_async(dispatch_get_main_queue(), { () -> Void in
            self?.tableView.pullToRefreshView?.stopAnimating()
        })
    })
}
```

**Comment by icodesign** [comment]
Thanks. (btw, I modified your markdown format a little bit for better visual effects)

**Comment by diegogarciar** [comment]
Awesome! don't forget the readme.md
